// <auto-generated>
// Auto-generated code by LocalizationEnumGenetator. DO NOT CHANGE IT.
// Shared Data Path: Assets/Localization/Table/Text2/Text2 Shared Data.asset
// </auto-generated>

using UnityEngine.Localization.Settings;
using UnityEngine.Localization.Tables;

namespace LangTextKey
{
    public enum Text2 : long
    {
        Key0 = 67977760768,
        Key1 = 70561452032,
    }
}

namespace UnityEngine.Localization.Settings
{
    public static class Text2LocalizedStringDatabaseExtentions
    {
        public static StringTable GetTable(this LocalizedStringDatabase database, LangTextKey.Text2 key)
         {
            var table = UnityEngine.Localization.Settings.LocalizationSettings.StringDatabase.GetTable("Text2");
            return table;
        }
    }

    public static class Text2StringTableExtentions
    {
        public static StringTableEntry GetEntry(this StringTable table, LangTextKey.Text2 key)
        {
            var entry = table.GetEntry((long)key);
            return entry;
        }
    }
}

namespace LangTextKey
{
    public static partial class LangTextKeyUtil
    {
        public static string GetLocalizedText(LangTextKey.Text2 key)
        {
            return LocalizationSettings.StringDatabase.GetTable(key).GetEntry(key).Value;
        }
    }
}
